#pragma once
#include <QSplitter>
#include <QFileSystemModel>
#include <QTreeView>
#include <QListView>
#include <QDir>
#include <QStatusBar>
#include <QLabel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QResizeEvent>
#include <QThread>
#include <QPalette>
#include <QDebug>
//#include <QMouseEvent>
#include <QFileDialog>
#include <QDir>
#include <QListView>
#include <QDirIterator>
#include <QScrollArea>
#include <QScrollBar>
#include <QQuickWidget>
#include <QPainter>
#include <QAction>
#include <QQuickItem>
#include <QStackedWidget>
#include <QComboBox>
#include <QFrame>
#include <QTextEdit>
#include <QDateTime>
#include <QStackedLayout>
#include <QPlainTextEdit>
#include <QLineEdit>
#include <QQuickView>

#include "debug.h"